### ISSUE TITLE
EntityExplodeEvent ClassCastException: java.lang.Integer cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by RoboMWM** [MLG-Fortress/PortalStick#3]
```
[15:51:46] [Server thread/ERROR]: Could not pass event EntityExplodeEvent to PortalStick v5.5
org.bukkit.event.EventException
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:46) ~[patched_1.11.jar:git-Paper-962]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[patched_1.11.jar:git-Paper-962]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[patched_1.11.jar:git-Paper-962]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517) [patched_1.11.jar:git-Paper-962]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:502) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.Explosion.a(Explosion.java:207) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.World.createExplosion(World.java:2012) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.WorldServer.createExplosion(WorldServer.java:1195) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.EntityCreeper.dn(EntityCreeper.java:211) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.EntityCreeper.A_(EntityCreeper.java:116) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.World.entityJoinedWorld(World.java:1760) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.World.g(World.java:1735) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.World.tickEntities(World.java:1552) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.WorldServer.tickEntities(WorldServer.java:620) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.MinecraftServer.D(MinecraftServer.java:885) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:403) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:749) [patched_1.11.jar:git-Paper-962]
	at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.java:648) [patched_1.11.jar:git-Paper-962]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at com.matejdro.bukkit.portalstick.Region.getString(Region.java:171) ~[?:?]
	at com.matejdro.bukkit.portalstick.listeners.PortalStickEntityListener.onEntityExplode(PortalStickEntityListener.java:100) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor964.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$1.execute(EventExecutor.java:44) ~[patched_1.11.jar:git-Paper-962]
	... 18 more

**Comment by RoboMWM** [comment]
Mitigated, and probably will need to update this plugin to use material names instead of ids... s000000n.....
